<a href="https://colab.research.google.com/github/anjalibajpai768-cell/AI-ML-INTERNSHIP/blob/main/Politics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORT LIBRARIES

In [ ]:
import pandas as pd
import numpy as np
from textblob import TextBlob
import plotly.graph_objects as go
import plotly.express as xp

LOADING DATA

In [ ]:
modi =pd.read_csv('/content/modi_reviews.csv')
rahul =pd.read_csv('/content/rahul_reviews.csv')

In [ ]:
modi.head()

   Unnamed: 0  ...                                              Tweet
0           0  ...  @anjanaomkashyap I am seeing you as future #bj...
1           1  ...  #LokSabhaElections2019 \n23rd May 2019 will re...
2           2  ...  #LokSabhaElections2019 \n23rd May 2019 will re...
3           3  ...  PM Modi creates a new record of being the only...
4           4  ...  @abhijitmajumder Appointment of Successor! \n\...

[5 rows x 3 columns]

In [ ]:
rahul.head()

   Unnamed: 0  ...                                              Tweet
0           0  ...  Wonder why no academic or journalist asks INC ...
1           1  ...  Congrats for the change #australiavotes2019 an...
2           2  ...  Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...
3           3  ...  @ajaymaken @RahulGandhi And as a final touch, ...
4           4  ...  #LokSabhaElections2019 Anyone not having mass ...

[5 rows x 3 columns]

In [ ]:
modi.sample()

       Unnamed: 0       User                                              Tweet
24348       24348  rkreddy_d  @nirmalsbhat @SushantBSinha @AshishSinghNews @...

In [ ]:
rahul.sample()

      Unnamed: 0  ...                                              Tweet
6115        6115  ...  @RahulGandhi #BJP #PMO #PulwamaAttack  You shu...

[1 rows x 3 columns]

In [ ]:
modi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25688 entries, 0 to 25687
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  25688 non-null  int64
 1   User        25683 non-null  object
 2   Tweet       25683 non-null  object
dtypes: int64(1), object(2)
memory usage: 602.2+ KB

In [ ]:
rahul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14261 entries, 0 to 14260
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  14261 non-null  int64
 1   User        14261 non-null  object
 2   Tweet       14261 non-null  object
dtypes: int64(1), object(2)
memory usage: 334.4+ KB

In [ ]:
modi.shape

(25688, 3)

In [ ]:
rahul.shape

(14261, 3)

In [ ]:
TextBlob(modi["Tweet"][10]).sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [ ]:
TextBlob(rahul["Tweet"][10]).sentiment

Sentiment(polarity=-0.3814697265625, subjectivity=0.375)

In [ ]:
modi['Tweet'] = modi['Tweet'].astype(str)
rahul['Tweet'] = rahul['Tweet'].astype(str)

def find_polarity(review):
  return TextBlob(review).sentiment.polarity

In [ ]:
modi['Polarity'] = modi['Tweet'].apply(find_polarity)
rahul['Polarity'] = rahul['Tweet'].apply(find_polarity)

In [ ]:
modi

       Unnamed: 0  ...  Polarity
0               0  ...  0.350000
1               1  ...  0.800000
2               2  ...  0.800000
3               3  ...  0.312121
4               4  ...  0.098788
...           ...  ...       ...
25683       25683  ...  0.000000
25684       25684  ...  0.209524
25685       25685  ... -0.700000
25686       25686  ...  0.000000
25687       25687  ... -0.213542

[25688 rows x 4 columns]

In [ ]:
rahul

       Unnamed: 0  ...  Polarity
0               0  ...  0.218750
1               1  ...  0.000000
2               2  ...  0.000000
3               3  ...  0.320000
4               4  ... -0.166667
...           ...  ...       ...
14256       14256  ...  0.000000
14257       14257  ... -0.500000
14258       14258  ...  0.080000
14259       14259  ...  0.080000
14260       14260  ...  0.080000

[14261 rows x 4 columns]

In [ ]:
modi['Label'] = np.where(modi['Polarity'] > 0, 'Positive', 'Negative')
modi['Label'][modi['Polarity'] == 0] = 'Neutral'

rahul['Label'] = np.where(rahul['Polarity'] > 0, 'Positive', 'Negative')
rahul['Label'][rahul['Polarity'] == 0] = 'Neutral'

/tmp/ipykernel_560/3333856115.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  modi['Label'][modi['Polarity'] == 0] = 'Neutral'
/tmp/ipykernel_560/3333856115.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modi['Label'][modi['Polarity'] == 0] = 'Neutral'
/tmp/ipykernel_560/3333856115.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rahul['Label'][rahul['Polarity'] == 0] = 'Neutral'
/tmp/ipykernel_560/3333856115.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rahul['Label'][rahul['Polarity'] == 0] = 'Neutral'

In [ ]:
neutral_modi = modi[modi['Polarity']==0.000]
remove_neutral_modi = modi['Polarity'].isin(neutral_modi['Polarity'])
modi.drop(modi[remove_neutral_modi].index,inplace= True)

In [ ]:
print(neutral_modi.shape)
print(modi.shape)

(8206, 5)
(17482, 5)

In [ ]:
neutral_rahul = rahul[rahul['Polarity']==0.000]
remove_neutral_rahul = rahul['Polarity'].isin(neutral_rahul['Polarity'])
rahul.drop(rahul[remove_neutral_rahul].index,inplace= True)

In [ ]:
print(neutral_rahul.shape)
print(rahul.shape)

(4894, 5)
(9367, 5)

In [ ]:
# making row counts to 9000
#for modi
np.random.seed(10)
remove_n = 8482
drop_indices = np.random.choice(modi.index, remove_n, replace=False)
df_modi = modi.drop(drop_indices)

In [ ]:
print(df_modi.shape)

(9000, 5)

In [ ]:
#for rahul
np.random.seed(10)
remove_n = 8482
drop_indices = np.random.choice(rahul.index, remove_n, replace=False)
df_rahul = rahul.drop(drop_indices)

In [ ]:
print(df_rahul.shape)

(885, 5)

PREDICTION FOR ELECTION

In [ ]:
modi_count = df_modi.groupby('Label').count()
modi_count

          Unnamed: 0  User  Tweet  Polarity
Label
Negative        2629  2629   2629      2629
Positive        6371  6371   6371      6371

In [ ]:
neg_modi = (modi_count['Polarity'][0]/1000)*100
pos_modi = (modi_count['Polarity'][1]/1000)*100
print(neg_modi)
print(pos_modi)

262.9
637.1

/tmp/ipykernel_560/886517993.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  neg_modi = (modi_count['Polarity'][0]/1000)*100
/tmp/ipykernel_560/886517993.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pos_modi = (modi_count['Polarity'][1]/1000)*100

In [ ]:
rahul_count = df_rahul.groupby('Label').count()
rahul_count

          Unnamed: 0  User  Tweet  Polarity
Label
Negative         285   285    285       285
Positive         600   600    600       600

In [ ]:
neg_rahul = (rahul_count['Polarity'][0]/1000)*100
pos_rahul = (rahul_count['Polarity'][1]/1000)*100
print(neg_rahul)
print(pos_rahul)

28.499999999999996
60.0

/tmp/ipykernel_560/1614968781.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  neg_rahul = (rahul_count['Polarity'][0]/1000)*100
/tmp/ipykernel_560/1614968781.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pos_rahul = (rahul_count['Polarity'][1]/1000)*100

In [ ]:
politicians = ['Modi','Rahul']

neg_list =[neg_modi,neg_rahul]
pos_list = [pos_modi,pos_rahul]

fig = go.Figure(data=[
    go.Bar(name='Negative', x=politicians, y=neg_list),
    go.Bar(name='Positive', x=politicians, y=pos_list)
])
# Change the bar mode
fig.update_layout(barmode = 'group')
fig.show()
#